ComplimentApp/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from django.conf import settings
from django.conf.urls.static import static

from apps.v1_0.views.users import InformationErrorApiView

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('', include('apps.v1_0.urls.template')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema-admin'),
    path('api/docs/', SpectacularSwaggerView.as_view(url_name='schema-admin'), name='swagger-ui'),
    re_path(r'api/docs/errors/?', InformationErrorApiView.as_view(), name='doc-error'),
    path('api/v1_0/', include('apps.v1_0.urls.all'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/models/phrases.py
import uuid

from django.db import models

from apps.models.users import User

RARITY = [
    (1, "common"),
    (2, "uncommon"),
    (3, "rare"),
    (4, "mythical"),
    (5, "legendary")
]

STATUSES = (
    (1, 'Published'),
    (0, 'BackLog')
)


class Collection(models.Model):
    name = models.CharField(max_length=256)
    status = models.IntegerField(choices=STATUSES, default=1)
    create_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name[:30]


class Phrase(models.Model):
    text = models.CharField(max_length=1024)
    rarity = models.IntegerField(choices=RARITY, default=1)
    status = models.IntegerField(choices=STATUSES, default=1)
    collection = models.ForeignKey(Collection, on_delete=models.PROTECT, null=True, blank=True, default=None)

    def __str__(self):
        return self.text[:50]


class OpenPhrase(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
    phrase = models.ForeignKey(Phrase, on_delete=models.CASCADE)
    open_date = models.DateTimeField(auto_now_add=True)
    is_watched = models.BooleanField(default=True)
    get_from = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='get_from',
                                 null=True, blank=True, default=None)
    left_to_share = models.IntegerField(default=3)

    def __str__(self):
        return f'{self.phrase.text} to {self.user.id}'

apps/templates/main_process/collection.html
{% extends 'base.html' %}
{% block extra_css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'apps/css/phrase/collection.css' %}">
{% endblock %}

{% block content %}

    <img src="{% static 'apps/files/less_icon.svg' %}" alt="return_svg" onclick="javascript:history.go(-1);"
         class="return_icon"/>
    {#available collections:#}
    {#    <ul>#}
    {#      {% for collection in collections %}#}
    {#          <li><a href="/phrase/{{ phrase.id }}/">{{ collection.name }}</a>, {{collection.get_status_display}} </li>#}
    {#      {% endfor %}#}
    {#      </ul>#}
    <div class="collection_card">
        <div class="text"> Collection</div>
        <div class="under_text"> try to get them all!</div>
    </div>

    <div class="card-container">
        {% for card in phrases_list %}
            <div class="card {% if forloop.first %}active{% endif %}">
                <div class="card-wrapper">
                    <div class="card-front">
                        <h2>7777</h2>
                    </div>
                    <div class="card-back">
                        <h2>{{ card.title }}</h2>
                        <p>{{ card.text }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="card-information">
        <h6>opened phrases:</h6>
        <p>{{ phrases_list.count }} / {{ phrase_number }}</p>
    </div>
    <script>
        const slider = document.querySelector('.card-container');
        let mouseDown = false;
        let startX, scrollLeft;

        let startDragging = function (e) {
            mouseDown = true;
            startX = e.pageX - slider.offsetLeft;
            scrollLeft = slider.scrollLeft;
        };
        let stopDragging = function (event) {
            mouseDown = false;
        };

        slider.addEventListener('mousemove', (e) => {
            e.preventDefault();
            if (!mouseDown) {
                return;
            }
            const x = e.pageX - slider.offsetLeft;
            const scroll = x - startX;
            slider.scrollLeft = scrollLeft - scroll;
        });

        // Add the event listeners
        slider.addEventListener('mousedown', startDragging, false);
        slider.addEventListener('mouseup', stopDragging, false);
        slider.addEventListener('mouseleave', stopDragging, false);
    </script>
{% endblock %}

apps/templates/main_process/index.html
{% extends 'base.html' %}
{% block extra_css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'apps/css/phrase/main.css' %}">
{% endblock %}

{% block content %}
    <div class="page">
    {% if today_phrase.is_opened %}
        <div class="collection_card animation_{{ today_phrase.phrase.rarity }}">
            <p>{{ today_phrase.phrase.text }}</p>

            <p class="card_rarity">rarity: {{ today_phrase.phrase.get_rarity_display  }}</p>
            <p class="card_id">card number: {{ today_phrase.phrase.id }}</p>
        </div>
    {% else %}
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="compliment_page">COMPLIMENT ME!!!</button>
            <div class="server_message">
                {% if errors %}
                    <ul class="errorlist" style="list-style-type: none">
                        {% for key, value in errors.items %}
                            <li>{{ value }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
        </form>

    {% endif %}
    <button id="Collection" class="collection small_buttons">My collection</button>

    <button id="Share_button" class="share small_buttons">Share with Friends</button>

    <button id="Guide" class="guide small_buttons">Guide</button>

    <button id="Profile" class="profile small_buttons">Profile</button>

    <script>
        document.getElementById("Collection").onclick = function () {
            location.href = "{% url 'collection' %}"
        };
    </script>
    <script>
        document.getElementById("Share_button").onclick = function () {
            {#var id = {{today_phrase.phrase.id}}#}
            location.href = "/share/" + {{ today_phrase.phrase.id }} +"/"
        };
    </script>
    <script>
        document.getElementById("Guide").onclick = function () {
            location.href = "{% url 'guide' %}"
        };
    </script>
    <script>
        document.getElementById("Profile").onclick = function () {
            location.href = "{% url 'profile' %}"
        };
    </script>
    </div>
{% endblock %}