ComplimentApp/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from django.conf import settings
from django.conf.urls.static import static

from apps.v1_0.views.users import InformationErrorApiView

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('', include('apps.v1_0.urls.template')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema-admin'),
    path('api/docs/', SpectacularSwaggerView.as_view(url_name='schema-admin'), name='swagger-ui'),
    re_path(r'api/docs/errors/?', InformationErrorApiView.as_view(), name='doc-error'),
    path('api/v1_0/', include('apps.v1_0.urls.all'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/models/tags.py
from django.db import models

from apps.models.phrases import Phrase
from apps.models.users import User


class Tag(models.Model):
    name = models.CharField(max_length=256, unique=True)


class TagToUser(models.Model):
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class TagToPhrase(models.Model):
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)
    phrase = models.ForeignKey(Phrase, on_delete=models.CASCADE)

apps/models/users.py
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.db import models


class User(AbstractUser):
    username_validator = UnicodeUsernameValidator()

    username = models.CharField(
        max_length=150,
        unique=True,
        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
        validators=[username_validator],
        error_messages={"unique": "A user with that username already exists."},
    )
    name = models.CharField(max_length=128, null=True, blank=True, default=None)
    last_name = models.CharField(max_length=128, null=True, blank=True, default=None)
    birthday = models.DateField(default=None, null=True, blank=True)
    email = models.EmailField(max_length=128, unique=True)
    password = models.CharField(max_length=128)
    is_active = models.BooleanField(default=True)


class Friend(models.Model):
    my = models.ForeignKey(User, on_delete=models.CASCADE, related_name='my')
    to = models.ForeignKey(User, on_delete=models.CASCADE, related_name='to')
    create_date = models.DateTimeField(auto_now_add=True)


class UserRecovery(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    code = models.CharField(max_length=128)

apps/templates/auth_process/forgot_code.html
{% extends 'base.html' %}
{% load i18n %}
{% block extra_css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'apps/css/auth/forgot_code.css' %}">
    <meta charset="utf-8">
    <title>Home page</title>
{% endblock %}
{% block content %}
    <img src="{% static 'apps/files/less_icon.svg' %}" alt="return_svg" onclick="javascript:history.go(-1);"
         class="return_icon"/>
    <div class="center_form">
        <div class="header">
            <h1>Reset password</h1>
            <p>Enter the code sent to your email and creat new password</p>
        </div>
        <form method="post">
            {% csrf_token %}
            <div class="login-form">
                <input type="text" name="code" id="id_code" required="true" autocomplete="off" placeholder="Code"
                       class="code base-input">
            </div>
            <div class="login-form">
                <input type="password" name="password" id="id_password" required="true" autocomplete="off"
                       placeholder="New password" class="password base-input">
            </div>
            <form action="{{ redirect_url }}" method="get">
                <button type="submit" class="signup button-form">Save!</button>
            </form>
        </form>
    </div>
{% endblock %}

apps/templates/auth_process/forgot_email.html
{% extends 'base.html' %}
{% load i18n %}
{% block extra_css %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'apps/css/auth/forgot_email.css' %}">
    <meta charset="utf-8">
    <title>Home page</title>
{% endblock %}

{% block content %}
    <img src="{% static 'apps/files/less_icon.svg' %}" alt="return_svg" onclick="javascript:history.go(-1);"
         class="return_icon"/>
    <div class="center_form">
        <div class="header">
            <h1>Forgot password?</h1>
            <p>Enter the email address associated with your account, and we will send you the password</p>
        </div>
        <form method="post">
            {% csrf_token %}
            <div class="login-form">
                <input type="email" name="email" id="id_email" required="true" autocomplete="off" placeholder="Email"
                       class="email base-input">
            </div>
            {{ form.errors }}
            <form action="{{ redirect_url }}" method="get">
                <button type="submit" class="signup button-form">Send!</button>
            </form>
        </form>
    </div>
{% endblock %}

apps/templates/auth_process/forgot_success.html
{% extends 'base.html' %}
{% load i18n %}
{% block extra_css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'apps/css/auth/forgot_success.css' %}">
    <meta charset="utf-8">
    <title>Home page</title>
{% endblock %}
{% block content %}
    <div class="center_form">
        <div class="header">
            <h1>Password reset</h1>
            <p>Your password has been reset successfully!</p>
        </div>
        <div class="under_text">
        </div>
        <img src="{% static 'apps/files/img.png' %}" alt="success" class="image">
        <form action="{{ redirect_url }}" method="get">
            <button class="signup button-form">Continue</button>
        </form>
    </div>
{% endblock %}

apps/templates/auth_process/login.html
{% extends 'base.html' %}
{% load i18n %}
{% block extra_css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'apps/css/auth/login.css' %}">
{% endblock %}

{% block content %}
    <div class="center_form">
        <div class="header">
            <h1>Login account</h1>
            <p>to continue</p>
        </div>

        <form method="post" autocomplete="off">
            {% csrf_token %}
            <div class="login-form">
                <input type="text" name="username" id="id_name" required="true" autofocus="true" autocomplete="off"
                       placeholder="Username" class="username base-input" onfocus="this.removeAttribute('readonly');">
            </div>
            <div class="login-form">
                <input type="password" name="password" id="id_password" required="true" autocomplete="off"
                       placeholder="Password" class="password base-input" onfocus="this.removeAttribute('readonly');">
            </div>
            <a href="{% url 'forgot1' %}" class="forgot-password">Forgot it?</a>
            <button type="submit" class="login button-form">Log in</button>
        </form>
        <a href="{% url 'registration' %}" class="redirect_link">sign up</a>
    </div>
{% endblock %}

apps/templates/auth_process/registration.html
{% extends 'base.html' %}
{% load i18n %}
{% block extra_css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'apps/css/auth/registration.css' %}">
{% endblock %}

{% block content %}
    <div class="center_form">
        <div class="header">
            <h1>Create account</h1>
            <p>to continue</p>
        </div>
        <form method="post" autocomplete="off">
            {% csrf_token %}
            <div class="login-form">
                <input type="text" name="username" id="id_username" required="true" autofocus="true" autocomplete="off"
                       placeholder="Username" class="username base-input" onfocus="this.removeAttribute('readonly');">

            </div>
            <div class="login-form">
                <input type="email" name="email" id="id_email" required="true" autocomplete="off" placeholder="Email"
                       class="email base-input"  onfocus="this.removeAttribute('readonly');">
            </div>
            <div class="login-form">
                <input type="password" name="password" id="id_password" required="true" autocomplete="off"
                       placeholder="Password" class="password base-input"  onfocus="this.removeAttribute('readonly');">
            </div>
            <button type="submit" class="signup button-form">Submit</button>
        </form>
        <a href="{% url 'login' %}" class="redirect_link">log in</a>
    </div>
{% endblock %}

apps/templates/auth_process/start_page.html
{% extends 'base.html' %}
{% block extra_css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'apps/css/auth/start page.css' %}">
{% endblock %}

{% block content %}
    <div class="center_form">
        <div class="header">
            <h1>COMPLIMENT</h1>
        </div>

        <button id="log_in" class="action_btn login button-form">Log in</button>
        <button id="sign_up" class="action_btn signup button-form">Sign up</button>

        <script>
            document.getElementById("log_in").onclick = function () {
                location.href = "{% url 'login' %}"
            };
        </script>
        <script>
            document.getElementById("sign_up").onclick = function () {
                location.href = "{% url 'registration' %}"
            };
        </script>
    </div>
{% endblock %}